### ISSUE TITLE
Can't parse and store checkboxes entries in an array

### ISSUE THREAD

**Issue by elhmn** [stefanbuck/github-issue-parser#20]
I would like to parse checkboxes entries and store them in an array.

I currently have an issue form containing this snippet 👇 
```yaml
  - type: checkboxes
    id: fav_frameworks
    attributes:
      label:  What are your favourite frameworks ?
      options:
        - label: React.js
        - label: jQuery
        - label: Express
        - label: Angular
        - label: Vue.js
        - label: ASP.NET Core
        - label: Flask
        - label: ASP.NET
        - label: Django
        - label: Spring
        - label: Angular.js
        - label: Laravel
        - label: Ruby on Rails
        - label: Gatsby
        - label: FastAPI
        - label: Symfony
        - label: Svelte
        - label: Drupal
```

And would like the output to be similar to:
```json
{
    "fav_frameworks": ["Laravel", "Svelte"]
}
```

The current behaviour would produces this:
```json
 {
    "laravel": true,
    "svelte": true,
 }
```
