### ISSUE TITLE
`github-issue-parser` doesn't take into consideration issues filed using `empty issue` button

### ISSUE THREAD

**Issue by jamacku** [stefanbuck/github-issue-parser#26]
When a user reports an issue using the `empty issue` button, `github-issue-parser` will parse the result without taking into consideration issue form template passed as input.

As shown here: https://github.com/systemd/systemd/issues/23968#issuecomment-1201019825

It would be great if `github-issue-parser` could check if the reported issue match provided the issue form template.

**Comment by stefanbuck** [comment]
Thanks for the hint. This is indeed an issue. Unfortunately there is no way to identify if an issue has been created using issue forms or not. At the end every issue is just markdown, which is also the reason why there is no edit form (yet). There was a discussion to include an identifier, but looks like there is still not such a thing. 

In a super early prototype (prior issue forms) I've tried to infer the issue template being used to create an issue. It worked for simple templates, but wasn't reliable at all. 

The best solution I can think of is to include a specific label in the issue form

```yaml
labels: [issue-form-bug-report]

title: "Bug report"
body:
...
```

and then add a conditional in the corresponding GitHub Action 

```yaml
jobs:
  parse-form:
    if: ${{ github.event.label.name == 'issue-form-bug-report' }}
   ...
```

I hope this helps.
