### ISSUE TITLE
3.2.2 file not found regression

### ISSUE THREAD

**Issue by jrobison-sb** [stefanbuck/github-issue-parser#74]
When I attempt to use the newly released version 3.2.2 of this action, it fails. This was working nicely for us on prior versions for a long time.

## Reproduction case

This workflow: https://github.com/jrobison-sb/devops-3113/blob/main/.github/workflows/example.yml

This issue form: https://github.com/jrobison-sb/devops-3113/blob/main/.github/ISSUE_TEMPLATE/example.yml?plain=1

Results in this workflow / this error: https://github.com/jrobison-sb/devops-3113/actions/runs/9320842003/job/25658517099#step:3:8

Thanks.

**Comment by gr2m** [comment]
hmm the reason is that the `dist/` folder does not exist in https://github.com/stefanbuck/github-issue-parser/tree/v3.2.0. Compare to https://github.com/stefanbuck/github-issue-parser/tree/v3.1.1 where it does exist. 

I recommend to use `stefanbuck/github-issue-parser@v3.1.1` for the time being. In order to fix this problem for good, I recommend we mirror the setup of https://github.com/actions/create-github-app-token. I won't have time to look into it myself right now though

**Comment by gr2m** [comment]
or better, use `stefanbuck/github-issue-parser@v3`

**Comment by jrobison-sb** [comment]
@gr2m thanks for your reply.

Yes, pinning `stefanbuck/github-issue-parser@v3.1.1` unblocked us on this, at least for now.

I would expect `stefanbuck/github-issue-parser@v3` to be the same thing as v3.2.0, since v3.2.0 is currently the latest release, though our desire to pin v3.2.0 isn't necessarily the same thing as pinning v3. We previously did use `@v3`, and got bit by [a breaking change which shipped with v3.2.0](https://github.com/stefanbuck/github-issue-parser/pull/73/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L15-R15). So as part of modifying our usage to fix that breaking change, we wanted specific version pins which will help us avoid similar breaking changes in the future.

**Comment by gr2m** [comment]
what is the breaking change though? It was definitely not intended, I thought this was an internal implementation detail

**Comment by jrobison-sb** [comment]
@gr2m 

The [breaking change](https://github.com/stefanbuck/github-issue-parser/pull/73/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L15-R15) is that the json result isn't in the home directory anymore, so `cat ${HOME}/issue-parser-result.json` doesn't work anymore. We had been successfully using this for a long time:
```
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/prep-for-software-update.yml # optional but recommended

      - name: Read input from the issue, just for ease of troubleshooting if something was wrong
        run: cat ${HOME}/issue-parser-result.json | jq -S .
```

But upon the release of v3.2.2, it broke (this comes from a non-public repo, not the same one I linked initially):
<img width="567" alt="image" src="https://github.com/stefanbuck/github-issue-parser/assets/39737211/1143326f-c311-4a49-8ab6-9eb02b864fb8">


On 3.2.2 the json result should now be referenced by way of `cat ${{ runner.temp }}/issue-parser-result.json`. We attempted to modify our usage and pin 3.2.2 at the same time, to protect us from similar issues in the future, and that's how I arrived at the missing `dist` folder.

 Thanks again for following up on this.
